// Mocks generated by Mockito 5.4.6 from annotations
// in nhom_3_damh_lttbdd/test/add_place_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:image_picker/image_picker.dart' as _i6;
import 'package:latlong2/latlong.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nhom_3_damh_lttbdd/model/category_model.dart' as _i4;
import 'package:nhom_3_damh_lttbdd/screens/add_places/service/add_place_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFetchedAddress_0 extends _i1.SmartFake
    implements _i2.FetchedAddress {
  _FakeFetchedAddress_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddPlaceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddPlaceService extends _i1.Mock implements _i2.AddPlaceService {
  MockAddPlaceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CategoryModel>> fetchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, []),
            returnValue: _i3.Future<List<_i4.CategoryModel>>.value(
              <_i4.CategoryModel>[],
            ),
          )
          as _i3.Future<List<_i4.CategoryModel>>);

  @override
  _i3.Future<_i2.FetchedAddress> fetchAddressDetails(_i5.LatLng? latLng) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAddressDetails, [latLng]),
            returnValue: _i3.Future<_i2.FetchedAddress>.value(
              _FakeFetchedAddress_0(
                this,
                Invocation.method(#fetchAddressDetails, [latLng]),
              ),
            ),
          )
          as _i3.Future<_i2.FetchedAddress>);

  @override
  _i3.Future<void> submitPlaceRequest({
    required String? userId,
    required _i5.LatLng? latLng,
    required String? name,
    required String? notes,
    required String? street,
    required String? ward,
    required String? city,
    required List<_i4.CategoryModel>? selectedCategories,
    required List<_i6.XFile>? selectedImages,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitPlaceRequest, [], {
              #userId: userId,
              #latLng: latLng,
              #name: name,
              #notes: notes,
              #street: street,
              #ward: ward,
              #city: city,
              #selectedCategories: selectedCategories,
              #selectedImages: selectedImages,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
