// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ltqUwfvc2947y005o1LBerRHzHC1XoQ',
    appId: '1:854202909819:web:cdd20fdeee341f8d360ede',
    messagingSenderId: '854202909819',
    projectId: 'flutterfirebase-5beb3',
    authDomain: 'flutterfirebase-5beb3.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-5beb3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-5beb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZftFjixf66hAdUK3VCZqiO-eZ3yNiK3c',
    appId: '1:854202909819:android:aa45632c54656440360ede',
    messagingSenderId: '854202909819',
    projectId: 'flutterfirebase-5beb3',
    databaseURL: 'https://flutterfirebase-5beb3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-5beb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXmzlXu4l5T4TWX9X_d-iA5uydKPqolAw',
    appId: '1:854202909819:ios:8897ec081d5be781360ede',
    messagingSenderId: '854202909819',
    projectId: 'flutterfirebase-5beb3',
    databaseURL: 'https://flutterfirebase-5beb3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-5beb3.firebasestorage.app',
    iosBundleId: 'com.example.nhom3DamhLttbdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXmzlXu4l5T4TWX9X_d-iA5uydKPqolAw',
    appId: '1:854202909819:ios:8897ec081d5be781360ede',
    messagingSenderId: '854202909819',
    projectId: 'flutterfirebase-5beb3',
    databaseURL: 'https://flutterfirebase-5beb3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-5beb3.firebasestorage.app',
    iosBundleId: 'com.example.nhom3DamhLttbdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ltqUwfvc2947y005o1LBerRHzHC1XoQ',
    appId: '1:854202909819:web:de9264c3606272f0360ede',
    messagingSenderId: '854202909819',
    projectId: 'flutterfirebase-5beb3',
    authDomain: 'flutterfirebase-5beb3.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-5beb3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-5beb3.firebasestorage.app',
  );
}
